### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by Diaga** [darsnack/SpikingNN.jl#3]
While working on #1, I got the following dependency errors one of which I noticed later was added in runtests.jl only.

Should these maybe added to dependencies in Project.toml?

- SNNlib.jl
- ImageIO and ImageMagick (Image attached)
- VisualRegressionTests.jl
- Plots,jl

![ImageIO and ImageMagick](https://user-images.githubusercontent.com/38937684/84674333-40526500-af44-11ea-95ff-89f1fccdd198.png)

**Comment by jpsamaroo** [comment]
These dependencies probably need to be added to the package's test dependencies: https://julialang.github.io/Pkg.jl/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above-1

**Comment by darsnack** [comment]
Did you rebase from upstream? I added the test dependencies at the same time as the SNNlib issue.

**Comment by Diaga** [comment]
Yes, I did a rebase and we are still missing ImageIO and ImageMagick as test dependency.

**Comment by darsnack** [comment]
Added those to upstream.
